// Code generated by "stringer -type=Command"; DO NOT EDIT.

package robot

import "strconv"

const (
	_Command_name_0 = "Advance"
	_Command_name_1 = "TurnLeft"
	_Command_name_2 = "TurnRight"
)

func (i Command) String() string {
	switch {
	case i == 65:
		return _Command_name_0
	case i == 76:
		return _Command_name_1
	case i == 82:
		return _Command_name_2
	default:
		return "Command(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
